debug: False
solver: 'cbc'

# zensus_url: 'https://ergebnisse.zensus2011.de/auswertungsdb/download?csv=dynTable&tableHash=statUnit=WOHNUNG;absRel=ANZAHL;ags=150010000000;agsAxis=X;yAxis=BAUJAHR_MZ,ZAHLWOHNGN_HHG,WOHNFLAECHE_10S&locale=DE'

# sources for raw data
data_raw:
  timeseries: 'data/timeseries.csv'
  scalars:
    parameters: 'data/parameters.csv'
  scenarios: 'data/scenarios.csv'

# Preprocessed data to use
data_preprocessed:
  timeseries:
    demand_heat: 'demand_heat/demand_heat_1998.csv'
    price_electricity_spot: 'price_electricity_spot/price_electricity_spot_2015.csv'
# optimisation settings
investment:
  invest_pth: False

# CHP representation
chp_repr: 'option_2'



